In [1]:
import pandas as pd
import numpy as np

# Creating a DataFrame

## Creating an array

### Option 1

In [2]:
# creating an array
data = np.array([[2, 8], [7, 1], [4, 6]])

In [3]:
# creating a dataframe
dataframe = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['column1', 'column2'])

In [4]:
# showing the dataframe
dataframe

      column1  column2
row1        2        8
row2        7        1
row3        4        6

### Option 2

In [5]:
# creating an array with list shape 
data = [[2, 8], [7, 1], [4, 6]]

In [6]:
# creating a dataframe
dataframe = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['column1', 'column2'])

In [7]:
# showing the dataframe
dataframe

      column1  column2
row1        2        8
row2        7        1
row3        4        6

## Creating a DataFrame from a dictionary

In [8]:
# lists used for example
countries = ['Germany', 'France', 'UK', 'Spain']
population = [83407000, 69082000, 69487000, 49801559]

In [9]:
# storing lists within a dictionary
dict_countries = {'Countries':countries, 'Population':population}

In [10]:
# creating the dataframe
df_populations = pd.DataFrame(dict_countries)

In [11]:
# showing the dataframe
df_populations

  Countries  Population
0   Germany    83407000
1    France    69082000
2        UK    69487000
3     Spain    49801559

## Creating a DataFrame from a CSV file

In [12]:
# reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')

In [13]:
# showing dataframe
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Displaying a Dataframe

In [14]:
# easiest way of showing dataframe
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [15]:
# showing first 5 rows
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [16]:
# showing last 5 rows
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [17]:
# showing first n rows
df_exams.head(8)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39

In [18]:
# showing last n rows
df_exams.tail(3)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [19]:
# getting access to the shape atribute
df_exams.shape

(1000, 8)

In [20]:
# display n rows 
pd.set_option('display.max_rows', 1000)

In [21]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
61,male,group A,some high school,free/reduced,none,39,39,34
62,male,group A,associate's degree,free/reduced,none,62,61,55
63,female,group C,associate's degree,standard,none,69,80,71
64,female,group D,some high school,standard,none,59,58,59
65,male,group B,some high school,standard,none,67,64,61
66,male,group D,some high school,free/reduced,none,45,37,37
67,female,group C,some college,standard,none,60,72,74
68,male,group B,associate's degree,free/reduced,none,61,58,56
69,female,group C,associate's degree,standard,none,39,64,57
70,female,group D,some college,free/reduced,completed,58,63,73
71,male,group D,some college,standard,completed,63,55,63
72,female,group A,associate's degree,free/reduced,none,41,51,48
73,male,group C,some high school,free/reduced,none,61,57,56
74,male,group C,some high school,standard,none,49,49,41
75,male,group B,associate's degree,free/reduced,none,44,41,38
76,male,group E,some high school,standard,none,30,26,22
77,male,group A,bachelor's degree,standard,completed,80,78,81
78,female,group D,some high school,standard,completed,61,74,72
79,female,group E,master's degree,standard,none,62,68,68
80,female,group B,associate's degree,standard,none,47,49,50
81,male,group B,high school,free/reduced,none,49,45,45
82,male,group A,some college,free/reduced,completed,50,47,54
83,male,group E,associate's degree,standard,none,72,64,63
84,male,group D,high school,free/reduced,none,42,39,34
85,female,group C,some college,standard,none,73,80,82
86,female,group C,some college,free/reduced,none,76,83,88
87,female,group D,associate's degree,standard,none,71,71,74
88,female,group A,some college,standard,none,58,70,67
89,female,group D,some high school,standard,none,73,86,82
90,female,group C,bachelor's degree,standard,none,65,72,74
91,male,group C,high school,free/reduced,none,27,34,36
92,male,group C,high school,standard,none,71,79,71
93,male,group C,associate's degree,free/reduced,completed,43,45,50
94,female,group B,some college,standard,none,79,86,92
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62
100,male,group B,some college,standard,none,79,67,67
101,male,group D,bachelor's degree,standard,completed,68,74,74
102,female,group D,associate's degree,standard,none,85,91,89
103,male,group B,high school,standard,completed,60,44,47
104,male,group C,some college,standard,completed,98,86,90
105,female,group C,some college,standard,none,58,67,72
106,female,group D,master's degree,standard,none,87,100,100
107,male,group E,associate's degree,standard,completed,66,63,64
108,female,group B,associate's degree,free/reduced,none,52,76,70
109,female,group B,some high school,standard,none,70,64,72
110,female,group D,associate's degree,free/reduced,completed,77,89,98
111,male,group C,high school,standard,none,62,55,49
112,male,group A,associate's degree,standard,none,54,53,47
113,female,group D,some college,standard,none,51,58,54
114,female,group E,bachelor's degree,standard,completed,99,100,100
115,male,group C,high school,standard,none,84,77,74
116,female,group B,bachelor's degree,free/reduced,none,75,85,82
117,female,group D,bachelor's degree,standard,none,78,82,79
118,female,group D,some high school,standard,none,51,63,61
119,female,group C,some college,standard,none,55,69,65
120,female,group C,bachelor's degree,standard,completed,79,92,89
121,male,group B,associate's degree,standard,completed,91,89,92
122,female,group C,some college,standard,completed,88,93,93
123,male,group D,high school,free/reduced,none,63,57,56
124,male,group E,some college,standard,none,83,80,73
125,female,group B,high school,standard,none,87,95,86
126,male,group B,some high school,standard,none,72,68,67
127,male,group D,some college,standard,completed,65,77,74
128,male,group D,master's degree,standard,none,82,82,74
129,female,group A,bachelor's degree,standard,none,51,49,51
130,male,group D,master's degree,standard,none,89,84,82
131,male,group C,some high school,free/reduced,completed,53,37,40
132,male,group E,some college,free/reduced,completed,87,74,70
133,female,group C,some college,standard,completed,75,81,84
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75
135,male,group C,bachelor's degree,standard,none,58,55,48
136,male,group B,some high school,standard,completed,51,54,41
137,male,group E,high school,standard,none,70,55,56
138,female,group C,associate's degree,standard,none,59,66,67
139,male,group D,some college,standard,completed,71,61,69
140,female,group D,some high school,standard,none,76,72,71
141,female,group C,some college,free/reduced,none,59,62,64
142,female,group E,some college,free/reduced,completed,42,55,54
143,male,group A,high school,standard,none,57,43,47
144,male,group D,some college,standard,none,88,73,78
145,female,group C,some college,free/reduced,none,22,39,33
146,male,group B,some high school,standard,none,88,84,75
147,male,group C,associate's degree,free/reduced,none,73,68,66
148,female,group D,bachelor's degree,standard,completed,68,75,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
150,male,group A,some high school,standard,completed,62,67,69
151,male,group A,bachelor's degree,standard,none,77,67,68
152,female,group B,associate's degree,standard,completed,59,70,66
153,male,group D,bachelor's degree,standard,none,54,49,47
154,male,group D,some high school,standard,none,62,67,61
155,female,group C,some college,standard,completed,70,89,88
156,female,group E,high school,free/reduced,completed,66,74,78
157,male,group B,some college,free/reduced,none,60,60,60
158,female,group B,associate's degree,standard,completed,61,86,87
159,male,group D,associate's degree,free/reduced,none,66,62,64
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78
168,female,group B,high school,standard,completed,68,83,78
169,female,group C,some college,free/reduced,completed,67,75,70
170,male,group A,high school,standard,completed,72,73,74
171,male,group E,some high school,standard,none,94,88,78
172,female,group D,some college,standard,none,79,86,81
173,female,group C,associate's degree,standard,none,63,67,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54
175,female,group C,master's degree,standard,completed,81,91,87
176,female,group B,high school,free/reduced,completed,46,54,58
177,female,group C,associate's degree,standard,completed,71,77,77
178,female,group B,master's degree,free/reduced,completed,52,70,62
179,female,group D,some high school,standard,completed,97,100,100
180,male,group C,master's degree,free/reduced,completed,62,68,75
181,female,group C,some college,free/reduced,none,46,64,66
182,female,group E,high school,standard,none,50,50,47
183,female,group D,associate's degree,standard,none,65,69,70
184,male,group C,some high school,free/reduced,completed,45,52,49
185,male,group C,associate's degree,free/reduced,completed,65,67,65
186,male,group E,high school,standard,none,80,76,65
187,male,group D,some high school,standard,completed,62,66,68
188,male,group B,some high school,free/reduced,none,48,52,45
189,female,group C,bachelor's degree,standard,none,77,88,87
190,female,group E,associate's degree,standard,none,66,65,69
191,male,group D,some college,standard,completed,76,83,79
192,female,group B,some high school,standard,none,62,64,66
193,male,group D,some college,standard,completed,77,62,62
194,female,group C,master's degree,standard,completed,69,84,85
195,male,group D,associate's degree,standard,none,61,55,52
196,male,group C,some high school,free/reduced,completed,59,69,65
197,male,group E,high school,free/reduced,none,55,56,51
198,female,group B,some college,free/reduced,none,45,53,55
199,female,group B,bachelor's degree,free/reduced,none,78,79,76
200,female,group C,associate's degree,standard,completed,67,84,86
201,female,group D,some college,free/reduced,none,65,81,77
202,male,group C,associate's degree,standard,none,69,77,69
203,female,group B,associate's degree,standard,none,57,69,68
204,male,group C,some college,standard,none,59,41,42
205,male,group D,some high school,standard,completed,74,71,78
206,male,group E,bachelor's degree,standard,none,82,62,62
207,male,group E,high school,standard,completed,81,80,76
208,female,group B,some college,free/reduced,none,74,81,76
209,female,group B,some college,free/reduced,none,58,61,66
210,male,group D,some high school,free/reduced,completed,80,79,79
211,male,group C,some college,free/reduced,none,35,28,27
212,female,group C,high school,free/reduced,none,42,62,60
213,male,group C,associate's degree,free/reduced,completed,60,51,56
214,male,group E,high school,standard,completed,87,91,81
215,male,group B,some high school,standard,completed,84,83,75
216,female,group E,associate's degree,free/reduced,completed,83,86,88
217,female,group C,high school,free/reduced,none,34,42,39
218,male,group B,high school,free/reduced,none,66,77,70
219,male,group B,some high school,standard,completed,61,56,56
220,female,group D,high school,standard,completed,56,68,74
221,male,group B,associate's degree,standard,none,87,85,73
222,female,group C,some high school,free/reduced,none,55,65,62
223,male,group D,some high school,standard,none,86,80,75
224,female,group B,associate's degree,standard,completed,52,66,73
225,female,group E,master's degree,free/reduced,none,45,56,54
226,female,group C,some college,standard,none,72,72,71
227,male,group D,high school,standard,none,57,50,54
228,male,group A,some high school,free/reduced,none,68,72,64
229,female,group C,some college,standard,completed,88,95,94
230,male,group D,some college,standard,none,76,64,66
231,male,group C,associate's degree,standard,none,46,43,42
232,female,group B,bachelor's degree,standard,none,67,86,83
233,male,group E,some high school,standard,none,92,87,78
234,male,group C,bachelor's degree,standard,completed,83,82,84
235,male,group D,associate's degree,standard,none,80,75,77
236,male,group D,bachelor's degree,free/reduced,none,63,66,67
237,female,group D,some high school,standard,completed,64,60,74
238,male,group B,some college,standard,none,54,52,51
239,male,group C,associate's degree,standard,none,84,80,80
240,male,group D,high school,free/reduced,completed,73,68,66
241,female,group E,bachelor's degree,standard,none,80,83,83
242,female,group D,high school,standard,none,56,52,55
243,male,group E,some college,standard,none,59,51,43
244,male,group D,some high school,standard,none,75,74,69
245,male,group C,associate's degree,standard,none,85,76,71
246,male,group E,associate's degree,standard,none,89,76,74
247,female,group B,high school,standard,completed,58,70,68
248,female,group B,high school,standard,none,65,64,62
249,male,group C,high school,standard,none,68,60,53
250,male,group A,some high school,standard,completed,47,49,49
251,female,group D,some college,free/reduced,none,71,83,83
252,female,group B,some high school,standard,completed,60,70,70
253,male,group D,master's degree,standard,none,80,80,72
254,male,group D,high school,standard,none,54,52,52
255,female,group E,some college,standard,none,62,73,70
256,female,group C,associate's degree,free/reduced,none,64,73,68
257,male,group C,associate's degree,standard,completed,78,77,77
258,female,group B,some college,standard,none,70,75,78
259,female,group C,master's degree,free/reduced,completed,65,81,81
260,female,group C,some high school,free/reduced,completed,64,79,77
261,male,group C,some college,standard,completed,79,79,78
262,female,group C,some high school,free/reduced,none,44,50,51
263,female,group E,high school,standard,none,99,93,90
264,male,group D,high school,standard,none,76,73,68
265,male,group D,some high school,free/reduced,none,59,42,41
266,female,group C,bachelor's degree,standard,none,63,75,81
267,female,group D,high school,standard,none,69,72,77
268,female,group D,associate's degree,standard,completed,88,92,95
269,female,group E,some college,free/reduced,none,71,76,70
270,male,group C,bachelor's degree,standard,none,69,63,61
271,male,group C,some college,standard,none,58,49,42
272,female,group D,associate's degree,free/reduced,none,47,53,58
273,female,group D,some college,standard,none,65,70,71
274,male,group B,some college,standard,completed,88,85,76
275,male,group C,bachelor's degree,standard,none,83,78,73
276,female,group C,some high school,standard,completed,85,92,93
277,female,group E,high school,standard,completed,59,63,75
278,female,group C,some high school,free/reduced,none,65,86,80
279,male,group B,bachelor's degree,free/reduced,none,73,56,57
280,male,group D,high school,standard,none,53,52,42
281,male,group D,high school,standard,none,45,48,46
282,female,group D,bachelor's degree,free/reduced,none,73,79,84
283,female,group D,some college,free/reduced,completed,70,78,78
284,female,group B,some high school,standard,none,37,46,46
285,male,group B,associate's degree,standard,completed,81,82,82
286,male,group E,associate's degree,standard,completed,97,82,88
287,female,group B,some high school,standard,none,67,89,82
288,male,group B,bachelor's degree,free/reduced,none,88,75,76
289,male,group E,some high school,standard,completed,77,76,77
290,male,group C,associate's degree,standard,none,76,70,68
291,male,group D,some high school,standard,none,86,73,70
292,male,group C,some high school,standard,completed,63,60,57
293,female,group E,bachelor's degree,standard,none,65,73,75
294,male,group D,high school,free/reduced,completed,78,77,80
295,male,group B,associate's degree,free/reduced,none,67,62,60
296,male,group A,some high school,standard,completed,46,41,43
297,male,group E,associate's degree,standard,completed,71,74,68
298,male,group C,high school,free/reduced,completed,40,46,50
299,male,group D,associate's degree,free/reduced,none,90,87,75
300,male,group A,some college,free/reduced,completed,81,78,81
301,male,group D,some high school,free/reduced,none,56,54,52
302,female,group C,associate's degree,standard,completed,67,84,81
303,male,group B,associate's degree,standard,none,80,76,64
304,female,group C,associate's degree,standard,completed,74,75,83
305,male,group A,some college,standard,none,69,67,69
306,male,group E,some college,standard,completed,99,87,81
307,male,group C,some high school,standard,none,51,52,44
308,female,group B,associate's degree,free/reduced,none,53,71,67
309,female,group D,high school,free/reduced,none,49,57,52
310,female,group B,associate's degree,standard,none,73,76,80
311,male,group B,bachelor's degree,standard,none,66,60,57
312,male,group D,bachelor's degree,standard,completed,67,61,68
313,female,group C,associate's degree,free/reduced,completed,68,67,69
314,female,group C,bachelor's degree,standard,completed,59,64,75
315,male,group C,high school,standard,none,71,66,65
316,female,group D,master's degree,standard,completed,77,82,91
317,male,group C,associate's degree,standard,none,83,72,78
318,male,group B,bachelor's degree,standard,none,63,71,69
319,female,group D,associate's degree,free/reduced,none,56,65,63
320,female,group C,high school,free/reduced,completed,67,79,84
321,female,group E,high school,standard,none,75,86,79
322,female,group C,some college,standard,none,71,81,80
323,female,group C,some high school,free/reduced,none,43,53,53
324,female,group C,high school,free/reduced,none,41,46,43
325,female,group C,some college,standard,none,82,90,94
326,male,group C,some college,standard,none,61,61,62
327,male,group A,some college,free/reduced,none,28,23,19
328,male,group C,associate's degree,standard,completed,82,75,77
329,female,group B,some high school,standard,none,41,55,51
330,male,group C,high school,standard,none,71,60,61
331,male,group C,associate's degree,standard,none,47,37,35
332,male,group E,associate's degree,standard,completed,62,56,53

In [22]:
# display first 5 and last 5 rows
pd.set_option('display.max_rows', 10)

In [23]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Basic Attributes, Methods and Functions

## Attributes

In [24]:
df_exams.shape

(1000, 8)

In [25]:
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [26]:
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [27]:
# data types of each column (objects are strings)
df_exams.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

## Methods

In [28]:
# showing first 5 columns
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [29]:
# showing the info of the dataframe
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [30]:
# describing basic statistics of the dataframe
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

## Functions

In [31]:
# obtaining the length of the dataframe (number of rows)
len(df_exams)

1000

In [32]:
# obtaining highest index in dataframe
max(df_exams.index)

999

In [33]:
# obtaining lowest index of the dataframe
min(df_exams.index)

0

In [34]:
# obtaining the data type
type(df_exams)

pandas.core.frame.DataFrame

In [35]:
# rounding the values of the dataset
round(df_exams, 2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Selecting one column

## Syntax 1

In [36]:
# select a column with [] (preferred way to select a column)
df_exams['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [37]:
# check out the data type of column
type(df_exams['gender'])

pandas.core.series.Series

In [38]:
# series: attributes and methods
df_exams['gender'].index
df_exams['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

# Syntax 2

In [39]:
# select a column with .
df_exams.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [40]:
# we can't select a column with multiple words with "."
#df_exams.math score

In [41]:
# select the same column using []
df_exams['math score']

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

# Selecting two or more columns

In [42]:
# select two columns using [[]]
df_exams[['race/ethnicity', 'writing score']]

    race/ethnicity  writing score
0          group B             74
1          group C             88
2          group B             93
3          group A             44
4          group C             75
..             ...            ...
995        group E             95
996        group C             55
997        group C             65
998        group D             77
999        group D             86

[1000 rows x 2 columns]

In [43]:
# check out the type of dataframe
type(df_exams[['race/ethnicity', 'writing score']])

pandas.core.frame.DataFrame

In [44]:
# select two  or more columns using [[]]
df_exams[['race/ethnicity', 'math score', 'reading score', 'writing score']]

    race/ethnicity  math score  reading score  writing score
0          group B          72             72             74
1          group C          69             90             88
2          group B          90             95             93
3          group A          47             57             44
4          group C          76             78             75
..             ...         ...            ...            ...
995        group E          88             99             95
996        group C          62             55             55
997        group C          59             71             65
998        group D          68             78             77
999        group D          77             86             86

[1000 rows x 4 columns]

In [45]:
# we can't select 2 or more columns with the "."
#df_exams.'race/ethnicity', 'writing score'

# Adding a new column to a Dataframe

## Adding a new column with a scalar value

In [46]:
# adding a new column to dataframe
df_exams['language score'] = 70

In [47]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

## Adding a new column with an array

The dataframe has 1000 rows, so an array with 1000 elements is needed

In [48]:
# creating an array of 1000 elements 
language_score = np.arange(0, 1000)

In [49]:
# length of array
len(language_score)

1000

In [50]:
# adding a new column to dataframe with an array
df_exams['language score'] = language_score

In [51]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [52]:
# creating 1000 random integer numbers between 0 and 100
int_language_score = np.random.randint(0, 100, size=1000)

In [53]:
# min value inclusive and max value exclusive 
print(min(int_language_score))
print(max(int_language_score))

0
99

In [54]:
# adding a new column to dataframe with an array
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,24
1,female,group C,some college,standard,completed,69,90,88,39
2,female,group B,master's degree,standard,none,90,95,93,27
3,male,group A,associate's degree,free/reduced,none,47,57,44,48
4,male,group C,some college,standard,none,76,78,75,65
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,99
996,male,group C,high school,free/reduced,none,62,55,55,57
997,female,group C,high school,free/reduced,completed,59,71,65,48
998,female,group D,some college,standard,completed,68,78,77,6
999,female,group D,some college,free/reduced,none,77,86,86,73

In [55]:
# creating random float numbers between 0 and 100
np.random.uniform(0, 100, size=1000)

array([12.70039505, 71.88110449, 91.3460193 , 31.39064811, 66.0967278 ,
       58.82735059, 62.37619157, 92.56238293, 72.69105486, 88.0999012 ,
       32.72732141, 42.79590911, 75.50015689, 44.62432394, 50.10326212,
       64.04771217,  6.74729616, 60.98057075, 96.27158996, 83.19612603,
       20.57820818, 34.7737111 , 41.39977543, 28.72848522, 81.50155925,
       87.16356912, 69.62478744, 42.2080044 , 92.75290531, 35.57692292,
       97.76601812, 96.86886106, 84.5870776 , 47.6476009 , 47.07497727,
       22.90275201, 37.57963101, 12.39840104, 30.96537891, 53.99971831,
       73.80589089, 94.81499903, 68.17303482, 34.041435  , 90.90981077,
        2.21844909, 64.55293858,  4.67522003, 13.30003646, 18.04405614,
        1.78345987,  3.72135685,  2.61760999, 37.58577954, 55.22175411,
       44.14925416, 58.14701959, 59.12143138, 94.21876786, 48.19650022,
       96.38353943, 79.79862609, 32.36899248, 30.73790328, 77.66258943,
       36.36482943, 25.14967299, 81.96611638, 50.12322612, 76.12319383,
       86.04385109, 11.52405835, 57.85063161, 89.30078093, 65.03616184,
       29.79880904, 96.09927652, 85.23059888, 62.40436423, 64.36950952,
        2.99597932, 74.51359796, 14.26904559, 60.12005847, 87.59842242,
       86.67483471, 51.50751672, 35.4962204 , 36.0205376 , 80.78134065,
       16.2278063 , 32.65610717, 14.74062057, 45.00121647, 87.70071628,
       84.61086292, 71.42187578, 17.76407994, 19.06080534, 76.57130241,
       70.79287737, 85.65189301,  0.38101511, 58.55222012, 70.94644426,
       19.33512185, 53.41541092, 99.36893229, 95.32621075,  9.38438551,
       28.25379604, 31.15845246,  5.11833652, 27.29309868, 80.999254  ,
       86.5081562 , 45.28684157, 43.53649102, 85.84466109, 31.30760576,
       74.35725336, 99.02405487, 16.58107668, 97.78899488, 10.05997238,
       68.53554644, 55.94941546, 45.47669914,  1.75711192, 25.1168191 ,
       86.37672278, 69.01285318, 41.22986381, 66.52225645, 51.70935594,
       89.95755494,  1.61658687, 59.90927984,  9.24483072, 89.06495889,
       31.89992169, 97.95992286,  6.95746678, 53.13410664, 58.57355299,
       38.99298445, 13.96503764, 49.05388593, 37.25176224, 19.35885158,
       25.88539818, 44.69018729, 92.70968387, 75.76236597, 86.82595697,
        2.01783173, 78.64990134, 26.94263575,  9.97795666, 83.79962306,
       67.22880546,  6.11136439, 89.63691158, 52.52657956, 14.4823035 ,
       71.70981399, 22.61178247, 47.02822503,  0.32043079, 95.93082209,
        3.88588692, 23.52917434, 85.86733967, 54.99102222, 23.62346724,
        3.61154754, 27.6125234 , 90.90525272, 14.78022666, 92.13580539,
       49.72913474,  7.71789551, 40.93563048, 65.69598412, 66.19704401,
       37.74828   , 21.09123261, 55.71409673, 74.71286817, 30.42810551,
       99.96524465, 81.59593944, 78.73324686, 79.61402734, 88.41630378,
        1.51307767, 96.69907169, 42.19142081, 99.0952587 , 97.40635387,
       27.76558695, 18.43182314, 65.68293   , 95.52966955, 62.12200311,
       94.51676566, 93.51420113,  7.71543479, 59.22144138, 52.55224284,
       35.04635137, 10.86713948, 35.51771123, 35.4653596 , 34.65815113,
       23.91686696, 36.39203299, 28.85567937, 45.9948695 , 81.36354117,
       60.35801616, 99.2597657 , 26.48634595, 47.24442571, 85.70299685,
       51.61814561, 50.24586615, 21.08447455, 13.62645551, 78.11910184,
       21.47258784, 96.53290667,  7.29022323, 43.55880227, 87.37931354,
       83.50681829, 72.5311716 , 45.68397764, 47.59112019, 56.92966034,
       31.82701122,  4.25799502, 72.80780493,  3.05214879, 33.61076154,
       59.1703478 , 26.09023445, 79.02542339, 92.55022766, 23.87934641,
       15.73814705,  8.23429827,  4.96505978, 29.978559  , 99.13006306,
       83.22788857,  4.16581386,  0.76648299, 35.47350448, 78.2903082 ,
       11.84565862, 17.91825613, 17.59543206, 57.65168718, 59.97814039,
        1.5287086 , 21.52274366, 81.23566273, 99.85628097, 93.17945503,
       29.42352901, 11.0338097 , 52.35886507, 58.98563829, 55.1715483 ,
       99.07646469, 53.96266036, 37.64577147, 71.48657273, 10.19779493,
       50.79263283, 87.52457076,  3.67844656, 70.44412014, 29.28701874,
       24.33902896, 14.99967508, 63.91358553, 73.59650613, 43.60864292,
       87.26002559, 50.21465426, 60.75350182,  7.69503594, 33.89059853,
       51.8007702 ,  9.19258506, 84.95665608, 58.60140419, 32.65948971,
       29.54789051, 84.37693221, 88.41956391, 19.30601708, 96.83582736,
       32.06659707, 54.42963984, 50.879857  , 27.09682044,  2.4748381 ,
       34.47074728, 22.55532437, 80.65776458, 33.56935923, 45.54882495,
       33.61730879, 10.11431102, 31.77313208, 29.47536943, 12.24009698,
       10.66784094,  9.87790966, 17.14222574, 66.57990742, 18.44456628,
       35.65338076, 91.31854605, 82.06869856, 49.10370777, 33.96216827,
       52.18682008, 63.30114768, 13.51522434, 25.91555478, 75.79733157,
       88.15968737, 52.6722112 , 22.24835542, 92.57692374,  4.45373481,
       66.71524714, 58.55534826, 33.81740859, 30.49560406, 13.49506629,
       84.16763489, 55.41805447, 64.73125527, 96.17309621, 58.06138346,
       79.25393978, 32.44927839, 90.27516821, 97.47388453,  5.7664902 ,
       78.39262493, 10.21368488, 41.00891384, 87.53157051, 50.33947515,
        5.77196594, 13.35223653, 61.88102673, 65.97377024, 90.01113045,
       63.81384047,  8.49571152, 48.50942485, 92.74052749, 32.92712198,
       32.23104128, 40.38314441,  8.5896138 , 69.63064958, 50.7199884 ,
       36.34126257, 70.7717084 , 26.90456624, 14.18912215, 38.56005314,
       81.42830224, 64.48325105, 49.3606062 , 19.74681291, 40.06305649,
       43.29819897, 65.45606036, 94.10389537, 82.92655327, 98.59508803,
        4.32737652, 14.07840692, 42.23651908, 43.78709199, 14.40744542,
       80.30770667, 76.53638096, 40.19405638, 68.43858413, 99.22135704,
       28.25833598, 75.43151835, 77.49055202, 68.87515206, 61.68556555,
       82.701893  , 92.39560687, 73.7184604 , 62.01659665, 37.89570006,
       50.49838676, 36.00198403, 60.01868878, 74.56140116, 87.0443033 ,
       88.90051058, 30.74451664, 61.72677151, 14.81648193, 65.42051953,
       39.81816383, 47.29240452, 60.1623858 , 12.22666441,  7.62500226,
       43.51082539, 13.18327444, 74.23950539, 71.37012767, 96.50770592,
       50.13798551, 50.11945835, 82.80849146, 14.64116746, 81.40732938,
       60.77379961, 85.26699612, 91.45157659, 43.32085433, 19.07077203,
       96.6211265 , 49.56891317, 69.96244693, 75.31408999, 21.74085272,
       13.08562353, 58.12698339, 42.35256143, 73.53950877, 73.29909533,
       72.55268448, 20.85173153, 81.49344979, 89.94772162,  6.51556701,
       62.10977382, 44.81060826,  0.77693601, 91.49319933, 26.96593475,
       38.56669851, 14.60823707, 50.78143231, 44.84639725, 15.9567167 ,
       82.67375638,  0.90955138, 38.16497764, 10.15506541, 60.39826217,
        4.91855693, 34.20018878, 14.13703661,  5.79177134, 10.5858031 ,
       83.01820571, 14.63584287, 49.81069396,  9.42710343, 63.66229862,
       76.99141853, 23.6339169 , 50.41746713, 54.57532565, 59.90096214,
       14.83012817, 15.39548296, 34.19222257, 62.79885566, 53.87901601,
       15.55291103, 74.62637954, 98.35053934, 28.10795191, 83.25755417,
       61.38219761, 13.47324047, 59.56125175, 68.79725777, 19.66042472,
       12.8120045 , 13.76035559,  7.16684416, 21.51559446, 86.68717465,
        5.21851882, 46.82578943,  1.13190496, 45.76386653, 17.89150095,
       64.94989529, 73.29892934, 79.69215518, 13.27242044, 15.54882054,
       86.67016996, 62.28674549, 17.61264067, 99.63761872, 41.96070144,
       43.93020596, 47.53148526, 76.03262129, 60.39696155, 17.57928286,
       85.71119649, 21.82594292,  9.02482213, 96.04714495, 86.03153378,
       12.47175498,  3.34815444, 83.98440579, 86.71928429, 34.47919508,
       72.25667091,  3.04500268, 22.9445206 , 78.82594293, 73.1826555 ,
        6.46739342, 32.52680464, 70.75387137, 28.27374067, 31.94156087,
       95.82980474,  2.95371127, 65.27826459, 77.25708744, 73.4958444 ,
        1.32974052, 66.31556496,  2.0073297 ,  3.08938482, 58.87115695,
       93.99159856, 69.90921752,  3.35827737, 13.90465912, 59.15943376,
       38.34355238, 44.54489952, 86.40703894, 25.08514885, 54.59482637,
       59.78162018, 83.01465769, 16.66740773, 79.11873366,  1.904011  ,
       80.96320734, 60.23460961, 14.45394878, 61.0406816 , 74.33344981,
       35.59838057,  2.98969743, 62.75469706, 92.38914959,  8.09558621,
       64.41009652, 14.67599119, 69.59324427, 68.48292978, 11.14812249,
       99.15968704, 93.80439032, 41.77686544, 41.37875156, 43.41933224,
       89.53911935, 25.77026927, 68.89487591, 79.49784972, 33.09883869,
       48.8807867 , 45.04896183, 36.14852866, 12.70996001, 47.89292509,
       85.82250889, 50.33152366, 30.82438154, 32.06516719,  0.82499829,
       75.9055437 , 45.55922056, 19.29111461, 77.16345273, 60.70243337,
       60.26833263, 37.77341686, 39.55150527, 82.58874674, 94.65506   ,
       91.06735988, 44.23315567, 81.34794579,  8.38926393, 99.11896129,
       81.72462333, 41.83513232, 14.02478313, 42.84635229,  7.35669447,
       67.62778191, 59.37032462, 44.75805234, 71.51164311, 38.8415794 ,
       64.01778369, 65.14721715, 71.44870667, 97.3204756 , 80.00160777,
       65.63804901, 54.94808312, 43.72607825, 96.11345068, 89.40085955,
       95.6788369 , 57.36681906, 75.32049074,  2.48600801, 61.72043645,
       94.94738034, 83.58500554, 27.84555327, 85.98153615, 53.94109436,
        4.66812069, 54.78592884, 55.43673076, 91.43911043, 81.6473535 ,
       91.17069172, 62.78282685, 47.26233828, 26.3626298 , 83.55452401,
       51.59653708, 14.22450536, 51.08400687, 72.59412431, 54.79016102,
       28.74967455,  5.42704374, 39.22473879, 46.27343739, 72.79756921,
       72.16485122, 57.02534323,  5.70045402, 66.43776213,  6.17486704,
        5.29463978, 96.05795226, 82.67434529, 89.58420263, 58.53089418,
       77.15772746, 79.26201335, 82.28203202, 52.49683832, 86.38642117,
        4.14890729,  2.98256844, 10.89501524, 47.00078583, 21.63797434,
       51.47092223, 18.49369764, 50.41327672, 33.27937156, 61.23679603,
       45.90508868, 53.78382025, 85.1155823 , 60.32782645, 47.92810413,
       12.84645095, 79.33142745, 42.78549789, 81.63966835, 51.97385647,
       48.92492512, 46.97430992, 17.26736469,  2.75943698, 16.32273836,
       73.92360831, 55.11804785, 77.68255112, 88.51954661, 58.11038232,
       16.17729977, 25.75298191, 83.76433427, 89.7740263 , 80.74848397,
       48.85429483, 18.99094024,  0.41874895,  8.31638343, 80.55188636,
       22.17671152, 68.97189228, 80.97160148,  8.22023195, 45.35191585,
       88.577424  , 38.05243467, 76.46861406, 16.46793435, 53.08799008,
       37.45005845, 76.0544423 , 43.95148797, 23.73915449, 55.55002822,
       27.9321893 , 13.0986461 , 33.09310123, 13.75872694, 58.23961195,
        9.3220185 , 17.16345261, 91.84878612,  5.02649349, 52.00300768,
       31.71443137, 61.5738047 , 62.92040354, 96.47418548, 62.33211256,
        5.48105082, 87.92139605, 15.55818682, 37.54165316, 15.05034296,
       97.43580115, 19.28352442, 90.77358057, 39.568531  , 78.23500769,
       30.63545499, 80.65659823, 94.58576781, 71.62276729, 50.17259297,
       39.81563936, 36.60498006, 94.79756404, 10.14666635, 18.38639268,
       50.80978758, 13.02131589, 98.28491481,  1.79540722, 31.95033463,
       88.88671356, 29.40085711, 36.97451932, 83.84776135, 33.03023056,
       47.89662138, 17.19118378,  3.13764515, 61.77937155,  9.58059503,
       37.74574916, 58.52986831,  5.0606934 , 85.48394913, 96.77977129,
       89.54930475, 78.87437659, 56.14431515, 72.84734644, 55.22419314,
       67.96558064, 20.96446007, 25.84732189, 92.24381581, 31.36686127,
       68.09471254, 51.86098971, 37.0206118 , 84.90983797, 78.28932149,
       68.20959639, 60.00114844, 30.88712284,  0.38346639, 74.10412751,
       95.10221402, 65.87159534, 43.10082167, 90.21759301, 83.31456227,
       94.54543864, 30.41596319, 58.7515748 , 48.43909728, 52.65563384,
        8.13288289, 20.30612549, 65.84686137, 29.42635321, 47.40838977,
       46.7665739 , 86.6727572 , 55.58221548, 64.47165826, 25.29330838,
       48.86789462, 68.13703262, 48.89394984, 63.92418877, 16.87673012,
       71.49571742, 63.05807178, 50.48362717, 65.02845429, 91.40643466,
       85.56100201, 92.68994153, 43.36797258, 98.61478393, 90.33541869,
       36.12085342, 17.32120272, 23.05670197, 77.44315086, 89.66099629,
        0.53029789, 89.15632421, 81.65486526, 68.24028618, 73.83964991,
       17.86086297, 27.50395967, 12.26602492, 15.87366722, 59.7477778 ,
       18.08860722, 85.26188743, 27.48562567, 39.77088386, 41.08883457,
       46.61962371, 23.38603606, 26.8720956 , 75.3044436 , 44.24142945,
       99.9827916 , 94.58104858, 11.93491489,  9.63468617, 44.32168676,
       97.21337415, 15.05494195, 28.38703351, 90.73563432, 64.63788789,
       64.26875956, 51.87859415, 78.42950876, 28.79793652, 22.67380798,
        7.87554917, 44.53434489, 39.48205095, 41.23487451, 32.83197042,
       64.05887428, 94.29892725, 83.17824916, 14.16091394,  5.54677523,
       55.24488219,  7.29185438, 60.90676094, 74.49433168, 94.85699027,
        3.66475602, 27.98178059, 19.39404784, 58.06963865, 53.38527135,
       20.98305677, 90.58365113, 61.0072212 , 22.06660849, 58.43261092,
       47.00532692, 74.99484925, 19.33884502, 97.59241033, 56.95015301,
        5.82461524, 87.88476042, 49.59173948, 11.57774408, 33.23128199,
       49.91451337, 50.66239303, 99.81835969,  4.09209944, 53.76143073,
       40.35766111,  6.55279487, 44.59233782, 87.63580789, 55.87327937,
       36.39616062, 29.51242893, 62.32413296, 66.19665319, 70.59543909,
       77.28434143,  4.13046207, 29.25383396, 41.73527099, 92.94774125,
       39.11390293, 85.81307654, 78.97672741, 22.90660208, 58.16942651,
       28.51533188, 16.07541239, 54.66088622, 56.78515427, 31.74009254,
       47.13548037, 56.02182046, 18.1988083 , 99.41471455, 30.44434171,
       88.82435121, 53.52884193, 64.80227089,  2.69930729, 11.65343907,
       78.9111544 , 88.35320034, 40.64205838, 12.39439535,  1.75101376,
       22.92768731, 42.56560925, 45.59992435, 71.06380818, 85.11115219,
       48.79052452, 31.6783976 , 49.80487802, 75.62988501, 76.50789006,
       88.93998304, 40.41849193, 19.06975702, 98.85071645, 18.10310062,
        4.44918712,  1.44279327, 15.52890092, 86.50146355, 97.0805865 ,
       10.1077988 , 65.10518736, 98.84397932, 77.84956573,  5.68445968,
       11.29652525, 46.70175269, 31.25065988, 81.36275013, 14.73774713])

## Adding a new column with assign()

Use the assign method when adding multiple columns in single line of code or when needed to overwrite the values of an existing column (best practice)
It returns a new object (copy) with all the original columns in addition to new ones

In [56]:
# creating random numbers for new score columns
score1 = np.random.randint(0, 100, size=1000)
score2 = np.random.randint(0, 100, size=1000)

In [57]:
# creating a series using the random numbers
series1 = pd.Series(score1, index=np.arange(0, 1000))
series2 = pd.Series(score2, index=np.arange(0, 1000))

In [58]:
series1

0      16
1      33
2      61
3      76
4      88
       ..
995    15
996    79
997     6
998    99
999    16
Length: 1000, dtype: int64

In [59]:
# using assign() to add multiple columns
df_exams = df_exams.assign(score1=series1, score2=series2)

In [60]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,24,16,22
1,female,group C,some college,standard,completed,69,90,88,39,33,33
2,female,group B,master's degree,standard,none,90,95,93,27,61,31
3,male,group A,associate's degree,free/reduced,none,47,57,44,48,76,21
4,male,group C,some college,standard,none,76,78,75,65,88,23
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,99,15,6
996,male,group C,high school,free/reduced,none,62,55,55,57,79,50
997,female,group C,high school,free/reduced,completed,59,71,65,48,6,67
998,female,group D,some college,standard,completed,68,78,77,6,99,46
999,female,group D,some college,free/reduced,none,77,86,86,73,16,70

## Adding a new column with insert()

Insert a new column at a specific position or index

In [61]:
# using insert() to add a column at a specific position 
df_exams.insert(1,'test', series1)

In [62]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,16,group B,bachelor's degree,standard,none,72,72,74,24,16,22
1,female,33,group C,some college,standard,completed,69,90,88,39,33,33
2,female,61,group B,master's degree,standard,none,90,95,93,27,61,31
3,male,76,group A,associate's degree,free/reduced,none,47,57,44,48,76,21
4,male,88,group C,some college,standard,none,76,78,75,65,88,23
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,15,group E,master's degree,standard,completed,88,99,95,99,15,6
996,male,79,group C,high school,free/reduced,none,62,55,55,57,79,50
997,female,6,group C,high school,free/reduced,completed,59,71,65,48,6,67
998,female,99,group D,some college,standard,completed,68,78,77,6,99,46
999,female,16,group D,some college,free/reduced,none,77,86,86,73,16,70

# Operations on Dataframes

## Math Operations

### Operations in columns

In [63]:
# Selecting a column and calculating total sum
df_exams['math score'].sum()

np.int64(66089)

In [64]:
# count, mean, std, max, min
print(df_exams['math score'].count())
print(df_exams['math score'].mean())
print(df_exams['math score'].std())
print(df_exams['math score'].max())
print(df_exams['math score'].min())

1000
66.089
15.163080096009468
100
0

In [65]:
# easier calculation with .decsribe
df_exams['math score'].describe()

count    1000.00000
mean       66.08900
std        15.16308
min         0.00000
25%        57.00000
50%        66.00000
75%        77.00000
max       100.00000
Name: math score, dtype: float64

### Operating in rows

In [66]:
# calculating the sum in a row
df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [67]:
# calculating the average score and assgning the result to a new column
df_exams['average score'] = (df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'])/3

In [68]:
df_exams = df_exams.round(2)
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average score
0,female,16,group B,bachelor's degree,standard,none,72,72,74,24,16,22,72.67
1,female,33,group C,some college,standard,completed,69,90,88,39,33,33,82.33
2,female,61,group B,master's degree,standard,none,90,95,93,27,61,31,92.67
3,male,76,group A,associate's degree,free/reduced,none,47,57,44,48,76,21,49.33
4,male,88,group C,some college,standard,none,76,78,75,65,88,23,76.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,15,group E,master's degree,standard,completed,88,99,95,99,15,6,94.00
996,male,79,group C,high school,free/reduced,none,62,55,55,57,79,50,57.33
997,female,6,group C,high school,free/reduced,completed,59,71,65,48,6,67,65.00
998,female,99,group D,some college,standard,completed,68,78,77,6,99,46,74.33
999,female,16,group D,some college,free/reduced,none,77,86,86,73,16,70,83.00

# The value_counts() method

In [69]:
# len function
len(df_exams['gender'])

1000

In [70]:
# .count() method
df_exams['gender'].count()

np.int64(1000)

In [71]:
# counting gender elements
df_exams['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [72]:
# return the relative frequency (divide all values by the sum of all values)
df_exams['gender'].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [73]:
# counting "parental level of education" elements by catagory
df_exams['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [74]:
# return relative frequency and round to 2 dp
df_exams['parental level of education'].value_counts(normalize=True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

# Sort a dataframe with sort_values()

In [75]:
# sort by one column
df_exams.sort_values(by='math score')

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average score
59,female,52,group C,some high school,free/reduced,none,0,17,10,86,52,0,9.00
980,female,53,group B,high school,free/reduced,none,8,24,23,39,53,12,18.33
17,female,54,group B,some high school,free/reduced,none,18,32,28,40,54,46,26.00
787,female,41,group B,some college,standard,none,19,38,32,30,41,85,29.67
145,female,77,group C,some college,free/reduced,none,22,39,33,50,77,38,31.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,male,21,group D,some college,standard,completed,100,97,99,38,21,79,98.67
623,male,0,group A,some college,standard,completed,100,96,86,4,0,38,94.00
451,female,44,group E,some college,standard,none,100,92,97,37,44,74,96.33
962,female,31,group E,associate's degree,standard,none,100,100,100,73,31,35,100.00
149,male,93,group E,associate's degree,free/reduced,completed,100,100,93,59,93,85,97.67

In [76]:
# sort descending by one column
df_exams.sort_values('math score', ascending=False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average score
962,female,31,group E,associate's degree,standard,none,100,100,100,73,31,35,100.00
625,male,21,group D,some college,standard,completed,100,97,99,38,21,79,98.67
458,female,37,group E,bachelor's degree,standard,none,100,100,100,52,37,23,100.00
623,male,0,group A,some college,standard,completed,100,96,86,4,0,38,94.00
451,female,44,group E,some college,standard,none,100,92,97,37,44,74,96.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,77,group C,some college,free/reduced,none,22,39,33,50,77,38,31.33
787,female,41,group B,some college,standard,none,19,38,32,30,41,85,29.67
17,female,54,group B,some high school,free/reduced,none,18,32,28,40,54,46,26.00
980,female,53,group B,high school,free/reduced,none,8,24,23,39,53,12,18.33
59,female,52,group C,some high school,free/reduced,none,0,17,10,86,52,0,9.00

In [77]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average score
0,female,16,group B,bachelor's degree,standard,none,72,72,74,24,16,22,72.67
1,female,33,group C,some college,standard,completed,69,90,88,39,33,33,82.33
2,female,61,group B,master's degree,standard,none,90,95,93,27,61,31,92.67
3,male,76,group A,associate's degree,free/reduced,none,47,57,44,48,76,21,49.33
4,male,88,group C,some college,standard,none,76,78,75,65,88,23,76.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,15,group E,master's degree,standard,completed,88,99,95,99,15,6,94.00
996,male,79,group C,high school,free/reduced,none,62,55,55,57,79,50,57.33
997,female,6,group C,high school,free/reduced,completed,59,71,65,48,6,67,65.00
998,female,99,group D,some college,standard,completed,68,78,77,6,99,46,74.33
999,female,16,group D,some college,free/reduced,none,77,86,86,73,16,70,83.00

In [78]:
# sort by descending by multiple columns 
df_exams.sort_values(['math score', 'reading score'], ascending=False, inplace=True)

In [79]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average score
149,male,93,group E,associate's degree,free/reduced,completed,100,100,93,59,93,85,97.67
458,female,37,group E,bachelor's degree,standard,none,100,100,100,52,37,23,100.00
916,male,95,group E,bachelor's degree,standard,completed,100,100,100,50,95,6,100.00
962,female,31,group E,associate's degree,standard,none,100,100,100,73,31,35,100.00
625,male,21,group D,some college,standard,completed,100,97,99,38,21,79,98.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,77,group C,some college,free/reduced,none,22,39,33,50,77,38,31.33
787,female,41,group B,some college,standard,none,19,38,32,30,41,85,29.67
17,female,54,group B,some high school,free/reduced,none,18,32,28,40,54,46,26.00
980,female,53,group B,high school,free/reduced,none,8,24,23,39,53,12,18.33
59,female,52,group C,some high school,free/reduced,none,0,17,10,86,52,0,9.00

In [80]:
# sort descending with key function
df_exams.sort_values('race/ethnicity', ascending=True, key=lambda col:col.str.lower())

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average score
741,female,48,group A,associate's degree,free/reduced,none,37,57,56,92,48,60,50.00
151,male,88,group A,bachelor's degree,standard,none,77,67,68,24,88,39,70.67
811,male,6,group A,high school,free/reduced,none,45,47,49,53,6,47,47.00
112,male,89,group A,associate's degree,standard,none,54,53,47,3,89,48,51.33
25,male,42,group A,master's degree,free/reduced,none,73,74,72,80,42,86,73.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,male,85,group E,some college,standard,none,68,72,65,28,85,22,68.33
915,female,5,group E,some college,standard,none,68,70,66,51,5,79,68.00
592,male,35,group E,bachelor's degree,standard,none,68,68,64,78,35,36,66.67
479,male,49,group E,associate's degree,standard,none,76,71,67,59,49,44,71.33
517,female,45,group E,some college,standard,completed,66,74,73,37,45,99,71.00

# set_index() and sort_index() methods

## Create Index

In [81]:
import random

In [82]:
# creating non-repetitive values for the index
new_index = np.arange(0, 1000)

In [83]:
# shuffling the index 
random.shuffle(new_index)

In [84]:
# create a new column with new index
df_exams['new_index'] = new_index
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average score,new_index
149,male,93,group E,associate's degree,free/reduced,completed,100,100,93,59,93,85,97.67,634
458,female,37,group E,bachelor's degree,standard,none,100,100,100,52,37,23,100.00,896
916,male,95,group E,bachelor's degree,standard,completed,100,100,100,50,95,6,100.00,40
962,female,31,group E,associate's degree,standard,none,100,100,100,73,31,35,100.00,895
625,male,21,group D,some college,standard,completed,100,97,99,38,21,79,98.67,616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,77,group C,some college,free/reduced,none,22,39,33,50,77,38,31.33,690
787,female,41,group B,some college,standard,none,19,38,32,30,41,85,29.67,497
17,female,54,group B,some high school,free/reduced,none,18,32,28,40,54,46,26.00,938
980,female,53,group B,high school,free/reduced,none,8,24,23,39,53,12,18.33,770
59,female,52,group C,some high school,free/reduced,none,0,17,10,86,52,0,9.00,120

## set index

In [85]:
# set new_index column as index
df_exams.set_index('new_index', inplace=True)
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average score
new_index,,,,,,,,,,,,,
634,male,93,group E,associate's degree,free/reduced,completed,100,100,93,59,93,85,97.67
896,female,37,group E,bachelor's degree,standard,none,100,100,100,52,37,23,100.00
40,male,95,group E,bachelor's degree,standard,completed,100,100,100,50,95,6,100.00
895,female,31,group E,associate's degree,standard,none,100,100,100,73,31,35,100.00
616,male,21,group D,some college,standard,completed,100,97,99,38,21,79,98.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...
690,female,77,group C,some college,free/reduced,none,22,39,33,50,77,38,31.33
497,female,41,group B,some college,standard,none,19,38,32,30,41,85,29.67
938,female,54,group B,some high school,free/reduced,none,18,32,28,40,54,46,26.00
770,female,53,group B,high school,free/reduced,none,8,24,23,39,53,12,18.33
120,female,52,group C,some high school,free/reduced,none,0,17,10,86,52,0,9.00

## sort index

In [86]:
# sort dataframe by new index
df_exams.sort_index(inplace=True)
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average score
new_index,,,,,,,,,,,,,
0,male,7,group E,some college,free/reduced,completed,49,52,51,76,7,68,50.67
1,female,70,group B,some high school,free/reduced,completed,74,90,88,54,70,45,84.00
2,female,87,group D,high school,standard,none,56,52,55,6,87,20,54.33
3,male,17,group D,associate's degree,standard,completed,87,84,85,23,17,85,85.33
4,female,29,group B,some high school,standard,none,82,82,80,31,29,20,81.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,7,group B,high school,standard,none,87,95,86,36,7,82,89.33
996,female,8,group D,some high school,standard,completed,61,74,72,3,8,6,69.00
997,male,31,group B,some high school,standard,completed,79,85,86,54,31,79,83.33
998,male,38,group D,bachelor's degree,standard,none,80,73,72,50,38,88,75.00
999,male,73,group C,some high school,standard,none,49,49,41,74,73,70,46.33

In [87]:
# sort descending my index
df_exams.sort_index(ascending=False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average score
new_index,,,,,,,,,,,,,
999,male,73,group C,some high school,standard,none,49,49,41,74,73,70,46.33
998,male,38,group D,bachelor's degree,standard,none,80,73,72,50,38,88,75.00
997,male,31,group B,some high school,standard,completed,79,85,86,54,31,79,83.33
996,female,8,group D,some high school,standard,completed,61,74,72,3,8,6,69.00
995,female,7,group B,high school,standard,none,87,95,86,36,7,82,89.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,female,29,group B,some high school,standard,none,82,82,80,31,29,20,81.33
3,male,17,group D,associate's degree,standard,completed,87,84,85,23,17,85,85.33
2,female,87,group D,high school,standard,none,56,52,55,6,87,20,54.33
1,female,70,group B,some high school,free/reduced,completed,74,90,88,54,70,45,84.00
0,male,7,group E,some college,free/reduced,completed,49,52,51,76,7,68,50.67

# Rename columns and Index with rename()

## Rename columns

In [88]:
# rename column and overwrite values of the dataframe
df_exams.rename(columns={'gender':'Gender'}, inplace=True)

In [89]:
# rename multiple columns 
df_exams = df_exams.rename(columns={'math score':'MS', 'reading score':'RS', 'writing score':'WS'})

In [90]:
df_exams

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,language score,score1,score2,average score
new_index,,,,,,,,,,,,,
0,male,7,group E,some college,free/reduced,completed,49,52,51,76,7,68,50.67
1,female,70,group B,some high school,free/reduced,completed,74,90,88,54,70,45,84.00
2,female,87,group D,high school,standard,none,56,52,55,6,87,20,54.33
3,male,17,group D,associate's degree,standard,completed,87,84,85,23,17,85,85.33
4,female,29,group B,some high school,standard,none,82,82,80,31,29,20,81.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,7,group B,high school,standard,none,87,95,86,36,7,82,89.33
996,female,8,group D,some high school,standard,completed,61,74,72,3,8,6,69.00
997,male,31,group B,some high school,standard,completed,79,85,86,54,31,79,83.33
998,male,38,group D,bachelor's degree,standard,none,80,73,72,50,38,88,75.00
999,male,73,group C,some high school,standard,none,49,49,41,74,73,70,46.33

## Rename index

In [91]:
# rename index 0, 1, 2 
df_exams.rename(index={0:'A', 1:'B', 2:'C'}, inplace=True)

In [92]:
df_exams.head(3)

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,language score,score1,score2,average score
new_index,,,,,,,,,,,,,
A,male,7,group E,some college,free/reduced,completed,49,52,51,76,7,68,50.67
B,female,70,group B,some high school,free/reduced,completed,74,90,88,54,70,45,84.00
C,female,87,group D,high school,standard,none,56,52,55,6,87,20,54.33