In [1]:
import pandas as pd 
import numpy as np

# 1

In [2]:
GDP = 200000000
Population = 2564
GDP_per_person = GDP/Population

In [3]:
print(GDP_per_person)

78003.12012480499

In [4]:
country1 = 'UK'
country2 = 'France'
country1_population = 67000000
country2_population = 80000000
country1_GDP = 40000000000000
country2_GDP = 34000000000000
country1_GDP_per_person = country1_GDP/country1_population 
country2_GDP_per_person = country2_GDP/country2_population
print(f"UK's GDP/person is {country1_GDP_per_person}, while France's GDP/person is {country2_GDP_per_person}")

UK's GDP/person is 597014.9253731343, while France's GDP/person is 425000.0

# 2

In [5]:
inflation = 1.03
price_of_bread = 1.5
price_of_bread_after1year = price_of_bread*inflation

In [6]:
price_of_bread_after1year

1.545

In [7]:
price_of_bread_after5year = price_of_bread*(inflation**5)

In [8]:
price_of_bread_after5year

1.7389111114500002

In [9]:
# calculating overall percentage change over 5 years
((price_of_bread_after5year - price_of_bread)/price_of_bread)*100

15.927407430000015

# 3

In [10]:
def compound_growth(value, percentage_change, years):
    x = value * ((percentage_change/100)+1)**years
    return x

In [11]:
compound_growth(100, 50, 1)

150.0

In [12]:
compound_growth(152, 66, 5)

1915.949368755201

# 4

In [13]:
GDPs = np.array([[3941, 4355, 4201, 4562, 4686, 5051], [2648, 2966, 2795, 3056, 3160, 3366], [2724, 3195, 3181, 3421, 3696, 4003]])

In [14]:
GDP_dataframe = pd.DataFrame(GDPs, index = ['Germany', 'France', 'UK'], columns = [2020, 2021, 2022, 2023, 2024, 2025])

In [15]:
GDP_dataframe

         2020  2021  2022  2023  2024  2025
Germany  3941  4355  4201  4562  4686  5051
France   2648  2966  2795  3056  3160  3366
UK       2724  3195  3181  3421  3696  4003

# 5

In [16]:
values = np.array([[200, 100], [560, 80], [800, 99]])

In [17]:
tax = 0.2

In [18]:
values_after_tax = values-(values*tax)

In [19]:
values_after_tax

array([[160. ,  80. ],
       [448. ,  64. ],
       [640. ,  79.2]])

In [20]:
price = np.array([20, 50, 160])
sales = np.array([150, 100, 20])
revenue = price*sales

In [21]:
revenue

array([3000, 5000, 3200])

In [28]:
costs_per_unit = np.array([13, 33, 89])
fixed_costs = 200+50+300
total_costs = costs_per_unit * sales

In [29]:
total_costs

array([1950, 3300, 1780])

In [30]:
profit = revenue - total_costs
profit

array([1050, 1700, 1420])

# 6

In [31]:
data = np.array([[20, 50], [44, 60]])

In [32]:
Resource_Matrix = pd.DataFrame(data, index=['bread', 'vegetables'], columns=['Oscar', 'Leo'])

In [33]:
Resource_Matrix

            Oscar  Leo
bread          20   50
vegetables     44   60